### ISSUE TITLE
Java.net.ConnectException: Connection refused: Connect

### ISSUE THREAD

**Issue by docker156** [Ragnaroek/dandelion#6]
Hi,
W10, Eclipse, SBCL, 2.0.0

If I try to evaluate my Lisp-Code, the following error message appears:

Java.net.ConnectException: Connection refused: Connect

Kind regards,
Martin

**Comment by Ragnaroek** [comment]
Do you have more of the error message? If you open the Error Log in Eclipse there should be more details on what went wrong.

**Comment by docker156** [comment]
Hi, 
it is really  amazing to get such an fast answer. Thank you very much. I hope, my English is good enough to answer in the right manner.

The following i found in the error log

1. Error

Missing requirement: Marketplace Client Core 1.3.1.v20140820-1706 (org.eclipse.epp.mpc.core 1.3.1.v20140820-1706) requires 'osgi.bundle; org.eclipse.equinox.util 1.0.500' but it could not be found
An exception stack trace is not available.

2. Error Initialising Connection

de.defmacro.dandelion.internal.core.connection.ConnectionException: java.net.ConnectException: Connection refused: connect
    at de.defmacro.dandelion.internal.core.connection.LispConnection.connect(LispConnection.java:122)
    at de.defmacro.dandelion.internal.core.connection.AbstractJob.ensureConnected(AbstractJob.java:134)
    at de.defmacro.dandelion.internal.core.connection.InitializationJob.run(InitializationJob.java:83)
    at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
Caused by: java.net.ConnectException: Connection refused: connect
    at java.base/sun.nio.ch.Net.connect0(Native Method)
    at java.base/sun.nio.ch.Net.connect(Net.java:503)
    at java.base/sun.nio.ch.Net.connect(Net.java:492)
    at java.base/sun.nio.ch.NioSocketImpl.connect(NioSocketImpl.java:588)
    at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:333)
    at java.base/java.net.Socket.connect(Socket.java:648)
    at java.base/java.net.Socket.connect(Socket.java:597)
    at java.base/java.net.Socket.<init>(Socket.java:520)
    at java.base/java.net.Socket.<init>(Socket.java:294)
    at de.defmacro.dandelion.internal.core.connection.LispConnection.connect(LispConnection.java:110)
    ... 3 more

Session Data:
eclipse.buildId=4.17.0.I20200902-1800
java.version=14.0.2
java.vendor=Oracle Corporation
BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=de_DE
Command-line arguments:  -os win32 -ws win32 -arch x86_64 -data file:/C:/Users/.../Eclipse/

3. Error in background evaluation

de.defmacro.dandelion.internal.core.connection.ConnectionException: java.net.ConnectException: Connection refused: connect
    at de.defmacro.dandelion.internal.core.connection.LispConnection.connect(LispConnection.java:122)
    at de.defmacro.dandelion.internal.core.connection.AbstractJob.ensureConnected(AbstractJob.java:134)
    at de.defmacro.dandelion.internal.core.connection.EvaluationJob.run0(EvaluationJob.java:124)
    at de.defmacro.dandelion.internal.core.connection.AbstractEvaluationJob.run(AbstractEvaluationJob.java:108)
    at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
Caused by: java.net.ConnectException: Connection refused: connect
    at java.base/sun.nio.ch.Net.connect0(Native Method)
    at java.base/sun.nio.ch.Net.connect(Net.java:503)
    at java.base/sun.nio.ch.Net.connect(Net.java:492)
    at java.base/sun.nio.ch.NioSocketImpl.connect(NioSocketImpl.java:588)
    at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:333)
    at java.base/java.net.Socket.connect(Socket.java:648)
    at java.base/java.net.Socket.connect(Socket.java:597)
    at java.base/java.net.Socket.<init>(Socket.java:520)
    at java.base/java.net.Socket.<init>(Socket.java:294)
    at de.defmacro.dandelion.internal.core.connection.LispConnection.connect(LispConnection.java:110)
    ... 4 more

Session Data:
eclipse.buildId=4.17.0.I20200902-1800
java.version=14.0.2
java.vendor=Oracle Corporation
BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=de_DE
Command-line arguments:  -os win32 -ws win32 -arch x86_64 -data file:/C:/Users/.../Eclipse/

**Comment by Ragnaroek** [comment]
Ok, looks the lisp environment isn't up or cannot be reached. Let's debug:
Can you start the lisp environment in a terminal? It should be located in your home folder under .p2/pool/plugins/de.defmacro.dandelion.env.sbcl.xxxxxx/binary/environment_sbcl_x_x_x. Could you please execute the binary with the command `./environment_sbcl_x_x_x 30666 NIL DEBUG" and report the output?

**Comment by super-tomcat** [comment]
> 
> 
> Ok, looks the lisp environment isn't up or cannot be reached. Let's debug:
> Can you start the lisp environment in a terminal? It should be located in your home folder under .p2/pool/plugins/de.defmacro.dandelion.env.sbcl.xxxxxx/binary/environment_sbcl_x_x_x. Could you please execute the binary with the command `./environment_sbcl_x_x_x 30666 NIL DEBUG" and report the output?

I got this:

debugger invoked on a TYPE-ERROR in thread
#<THREAD "main thread" RUNNING {1001400523}>:
  The value
    #<SB-KERNEL:UNKNOWN-TYPE LOG4CL-IMPL:APPENDER>
  is not of type
    SB-KERNEL:CLASSOID

Type HELP for debugger help, or (SB-EXT:EXIT) to exit from SBCL.

restarts (invokable by number or by possibly-abbreviated name):
  0: [ABORT] Exit from the current thread.

(SB-KERNEL:CLASSOID-TYPEP #<SB-KERNEL:LAYOUT for LOG4CL-IMPL:DAILY-FILE-APPENDER {1002D82013}> #<SB-KERNEL:UNKNOWN-TYPE LOG4CL-IMPL:APPENDER> #<LOG4CL-IMPL:DAILY-FILE-APPENDER {1002F50E83}>)
0]

**Comment by docker156** [comment]
Hi,


I found .p2\pool\plugins\de.defmacro.dandelion.env.sbcl.win32.x86_2.0.0\binary\environment_sbcl_2.0.0.exe 

I got exactly the same output:

debugger invoked on a TYPE-ERROR in thread
#<THREAD "main thread" RUNNING {1001400523}>:
  The value
    #<SB-KERNEL:UNKNOWN-TYPE LOG4CL-IMPL:APPENDER>
  is not of type
    SB-KERNEL:CLASSOID

Type HELP for debugger help, or (SB-EXT:EXIT) to exit from SBCL.

restarts (invokable by number or by possibly-abbreviated name):
  0: [ABORT] Exit from the current thread.

(SB-KERNEL:CLASSOID-TYPEP #<SB-KERNEL:LAYOUT for LOG4CL-IMPL:DAILY-FILE-APPENDER {1002D82013}> #<SB-KERNEL:UNKNOWN-TYPE LOG4CL-IMPL:APPENDER> #<LOG4CL-IMPL:DAILY-FILE-APPENDER {1002F50E83}>)
0]

Thanks.

**Comment by Ragnaroek** [comment]
Yes, something is broken in the windows build. I can also confirm this on my windows installation.
Will take a look.

**Comment by Ragnaroek** [comment]
@docker156 @super-tomcat I tried to reproduce this error on windows. Just compiled the binary again and now it seems to work. Maybe something in the dependencies was updated. I uploaded the new Windows version as 2.0.1. Can you check if this is working for you now?

**Comment by super-tomcat** [comment]
Unfortunately having just changed computers i no longer use Eclipse or have it installed so i am not able to test
